/* eslint-disable max-len */
export const MockNews = [
  {
    data_publicacao: '18/10/2023 09:00:00',
    destaque: true,
    editorias: 'economicas',
    id: 38137,
    imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_10\\/pmc-set-thumb-alerrandre-barros.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_10\\/pmc-set-home-alerrandre-barros.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
    introducao: 'O conjunto de atividades que compõem o mix de lojas de departamentos foram os que mais contribuíram para resultado no mês - Foto: Acervo IBGE O volume de vendas do comércio em agosto variou -0,2% frente a julho de 2023. Na comparação com agosto de 2022,...',
    link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/38137-vendas-do-comercio-mantem-estabilidade-variando-0-2-em-agosto.html',
    produto_id: 9227,
    produtos: '9227|Pesquisa Mensal de Comércio|pesquisa-mensal-de-comercio|2075',
    produtos_relacionados: '9227',
    tipo: 'Notícia',
    titulo: 'Vendas do comércio mantêm estabilidade variando -0,2% em agosto',
  },
  {
    data_publicacao: '18/10/2023 09:00:00',
    destaque: true,
    editorias: 'economicas',
    id: 38136,
    imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PMC_release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PMC_release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
    introducao: 'Em agosto de 2023, o volume de vendas do comércio variou -0,2% frente a julho, na série com ajuste sazonal, após alta de 0,7% em julho de 2023. A média móvel trimestral, depois de variar de 0,1% no trimestre encerrado em julho de 2023, voltou a...',
    link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/38136-vendas-no-varejo-variam-0-2-em-agosto.html',
    produto_id: 9227,
    produtos: '9227|Pesquisa Mensal de Comércio|pesquisa-mensal-de-comercio|2075',
    produtos_relacionados: '9227',
    tipo: 'Release',
    titulo: 'Vendas no varejo variam -0,2% em agosto',
  },
  {
    data_publicacao: '17/10/2023 15:17:46',
    destaque: true,
    editorias: 'ibge',
    id: 38135,
    imagens: '{"image_intro":"images\\/agenciadenoticias\\/ibge\\/2023_10\\/caravana-rs-home.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/ibge\\/2023_10\\/caravana-rs-home.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
    introducao: 'O IBGE participará, nos dias 19 e 20 de outubro, da Caravana Federativa, no Centro de Eventos FIERGS, da Federação das Indústrias do Estado do Rio Grande do Sul, em Porto Alegre (RS). Com palestras e oficinas apresentadas por representantes de diversos...',
    link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/38135-ibge-estara-presente-na-edicao-de-porto-alegre-rs-da-caravana-federativa.html',
    produto_id: 0,
    produtos: '',
    produtos_relacionados: '',
    tipo: 'Notícia',
    titulo: 'IBGE estará presente na edição de Porto Alegre (RS) da Caravana Federativa',
  },
  {
    data_publicacao: '17/10/2023 09:00:00',
    destaque: true,
    editorias: 'economicas',
    id: 38126,
    imagens: '{"image_intro":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_10\\/PMS-THUMB_LiciaR.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_10\\/PMS-HOME_LiciaR.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
    introducao: 'Gestão de portos e terminais exerceu a principal influência negativa sobre o resultado do setor de serviços no país. Foto: Licia Rubinstein/Agência IBGE Notícias Em agosto, o volume de serviços prestados no país recuou 0,9% frente ao mês anterior, após...',
    link: 'http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/38126-servicos-recuam-0-9-em-agosto-apos-tres-altas-consecutivas.html',
    produto_id: 9229,
    produtos: '9229|Pesquisa Mensal de Serviços|pesquisa-mensal-de-servicos|2076',
    produtos_relacionados: '9229',
    tipo: 'Notícia',
    titulo: 'Serviços recuam 0,9% em agosto, após três altas consecutivas ',
  },
  {
    data_publicacao: '17/10/2023 09:00:00',
    destaque: true,
    editorias: 'economicas',
    id: 38125,
    imagens: '{"image_intro":"images\\/agenciadenoticias\\/releases\\/PMS_Release.png","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\\/agenciadenoticias\\/releases\\/PMS_Release.png","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}',
    introducao: 'Em agosto de 2023, o volume de serviços no Brasil caiu 0,9% frente a julho, na série com ajuste sazonal, após ter acumulado um ganho de 2,1% no período maio-julho. O setor de serviços está 11,6% acima do nível de fevereiro de 2020 (pré-pandemia) e 1,9%...',
    link: 'http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/38125-volume-dos-servicos-recua-0-9-em-agosto.html',
    produto_id: 9229,
    produtos: '9229|Pesquisa Mensal de Serviços|pesquisa-mensal-de-servicos|2076',
    produtos_relacionados: '9229',
    tipo: 'Release',
    titulo: 'Volume dos Serviços recua 0,9% em agosto',
  },

];
